# Generated by Django 3.2.2 on 2021-05-06 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('availability', models.BooleanField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 22, 13, 58, 422425, tzinfo=utc), verbose_name='last modified')),
                ('validity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('availability', models.BooleanField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 22, 13, 58, 423445, tzinfo=utc), verbose_name='last modified')),
                ('validity', models.BooleanField(default=True)),
                ('content', models.CharField(blank=True, max_length=10000)),
                ('blob', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.user')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('category', models.CharField(choices=[('proc', 'Procedure'), ('prop', 'Property'), ('lemm', 'Lemma'), ('assr', 'Assertion'), ('invr', 'Invariant'), ('prec', 'Precondition'), ('post', 'Postcondition')], max_length=4)),
                ('status', models.CharField(choices=[('pro', 'Proved'), ('inv', 'Invalid'), ('cex', 'CounterExample'), ('unc', 'Unchecked')], max_length=3)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 22, 13, 58, 425397, tzinfo=utc), verbose_name='last modified')),
                ('validity', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.file')),
                ('status_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.status_data')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.user'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.directory'),
        ),
    ]
