# Generated by Django 3.2.2 on 2021-05-18 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 22, 14, 15, 606871, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 22, 14, 15, 607906, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='section',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 22, 14, 15, 609941, tzinfo=utc), verbose_name='last modified'),
        ),
    ]
