# Generated by Django 3.2.2 on 2021-05-20 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_auto_20210519_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='number',
            new_name='line',
        ),
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 5, 7, 769502, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 5, 7, 770502, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='section',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 5, 7, 772525, tzinfo=utc), verbose_name='last modified'),
        ),
    ]
