# Generated by Django 3.2.2 on 2021-05-20 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_auto_20210520_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 35, 47, 280969, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 35, 47, 281935, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='section',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 14, 35, 47, 283650, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='status_data',
            name='field',
            field=models.TextField(blank=True),
        ),
    ]
