# Generated by Django 3.2.2 on 2021-05-20 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_auto_20210520_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 22, 34, 6, 936003, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 22, 34, 6, 936925, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='section',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 22, 34, 6, 938608, tzinfo=utc), verbose_name='last modified'),
        ),
    ]
