# Generated by Django 3.2.2 on 2021-05-20 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_auto_20210521_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 23, 34, 0, 921052, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 23, 34, 0, 921996, tzinfo=utc), verbose_name='last modified'),
        ),
    ]
