# Generated by Django 3.2.2 on 2021-05-21 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0006_auto_20210521_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 0, 58, 5, 972461, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 0, 58, 5, 973385, tzinfo=utc), verbose_name='last modified'),
        ),
    ]
